"""Initial SQLite DB

Revision ID: 6d190e4b1049
Revises: 
Create Date: 2026-04-17 15:22:08.604314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d190e4b1049'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost_7d', sa.Numeric(), nullable=False),
    sa.Column('cpu_avg_7d', sa.Float(), nullable=True),
    sa.Column('memory_avg_7d', sa.Float(), nullable=True),
    sa.Column('network_bytes_7d', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('resource_metadata', sa.JSON(), nullable=False),
    sa.Column('waste_score', sa.Float(), nullable=True),
    sa.Column('waste_tier', sa.String(), nullable=True),
    sa.Column('carbon_g_co2_7d', sa.Float(), nullable=True),
    sa.Column('carbon_intensity_score', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resources_account_id'), 'resources', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_account_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
